### ISSUE TITLE
Improve documentation on supported options

### ISSUE THREAD

**Issue by talonx** [ansible-community/ansible-bender#165]
There is a lack of documentation on what options we can pass under the ansible_bender var in a playbook. E.g. the https://pypi.org/project/ansible-bender/ page mentions some options but it would be good to have an exhaustive list. 

I presume the only way today to get this list is to look at the source code.

**Comment by TomasTomecek** [comment]
It is documented separately in this document: https://github.com/ansible-community/ansible-bender/blob/master/docs/configuration.md

The link to the document is present over here: https://github.com/ansible-community/ansible-bender/blob/master/README.md#configuration

Please use github readme as the source of truth instead of the PyPI landing page.

**Comment by talonx** [comment]
Great, thanks.
