### ISSUE TITLE
RFE: Implement Koji Content Generator

### ISSUE THREAD

**Issue by LorbusChris** [ansible-community/ansible-bender#60]
This is just an idea that crossed my mind.

Maybe `ab` could replace `OSBS`/`atomic-reactor` (which still relies on Docker)?

References:
https://docs.pagure.org/koji/content_generators/
https://docs.pagure.org/koji/content_generator_metadata/

WDYT?
Feel free to close if this falls under the `won't fix` category!

**Comment by TomasTomecek** [comment]
> Maybe ab could replace OSBS/atomic-reactor (which still relies on Docker)?

That's completely unreal :D I'll tell you that. I treat ab as a standalone tool.

atomic-reactor is very pluggable, it would make sense to do a [build-step plugin](https://github.com/projectatomic/atomic-reactor/blob/master/docs/plugins.md#buidstep-plugins) which would utilize ab

Oh, you [wrote](https://github.com/projectatomic/atomic-reactor/pull/1151) the buildah buildstep plugin for reactor, nice! So yeah, it could be nice to do the same thing for bender. But I feel like it's too soon for such a thing. Especially when #58 is still WIP.

But thanks for your suggestion.

**Comment by TomasTomecek** [comment]
I'm going to close this issue since I have no intention in implementing this. Bender is meant to be a standalone tool. On the other hand it's true that it supports building within an openshift build pod and I'm planning to write integration with knative. As for koji, I'd still prefer if the integration was done inside atomic-reactor and not bender.

Please reopen if you disagree and we can discuss some more. @LorbusChris, thanks for taking time to open this.
